package rugbyniela.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Address;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface AddressRepository extends JpaRepository<Address, Long>, JpaSpecificationExecutor<Address> {

	Optional<Address> findAddressByStreetAndCityAndPostalCodeAndDescription(
			String Street,
			String city,
			String postalCode,
			String description);
}
