package rugbyniela.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Bet;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface BetRepository extends JpaRepository<Bet, Long>, JpaSpecificationExecutor<Bet> {
	@Query("""
	        SELECT b FROM Bet b
	        WHERE b.match.matchDay.id = :matchDayId
	    """)
	List<Bet> findByMatchDayId(@Param("matchDayId") Long matchDayId);

}
