package rugbyniela.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.CoalitionMatchDayScore;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface CoalitionMatchDayScoreRepository extends JpaRepository<CoalitionMatchDayScore, Long>, JpaSpecificationExecutor<CoalitionMatchDayScore> {

}
