package rugbyniela.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Coalition;
import rugbyniela.entity.pojo.CoalitionRequest;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface CoalitionRepository extends JpaRepository<Coalition, Long>, JpaSpecificationExecutor<Coalition> {

	Page<Coalition> findByActive(boolean active, Pageable pageable);
}
