package rugbyniela.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.CoalitionRequest;

/**
* Generated by Spring Data Generator on 13/01/2026
*/
@Repository
public interface CoalitionRequestRepository extends JpaRepository<CoalitionRequest, Long>, JpaSpecificationExecutor<CoalitionRequest> {
	Page<CoalitionRequest> findByCoalitionId(Long coalitionId, Pageable pageable);
	boolean existsByUserIdAndCoalitionId(Long userId, Long coalitionId);
}
