package rugbyniela.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.DivisionBet;

/**
* Generated by Spring Data Generator on 11/12/2025
*/
@Repository
public interface DivisionBetRepository extends JpaRepository<DivisionBet, Long>, JpaSpecificationExecutor<DivisionBet> {

}
