package rugbyniela.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Division;
import rugbyniela.entity.pojo.Season;
import rugbyniela.entity.pojo.Team;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface DivisionRepository extends JpaRepository<Division, Long>, JpaSpecificationExecutor<Division> {

	Page<Division> findBySeason(Season season, Pageable pageable);

	Optional<Division> findByIdAndSeason(Long id, Season season);
	
	@Query("SELECT t FROM Division d JOIN d.teams t WHERE d.season = :season")
	Page<Team> findTeamsBySeason(@Param("season") Season season, Pageable pageable);


}
