package rugbyniela.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.MatchDay;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface MatchDayRepository extends JpaRepository<MatchDay, Long>, JpaSpecificationExecutor<MatchDay> {

	
}
