package rugbyniela.repository;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Match;
import rugbyniela.entity.pojo.Season;
import rugbyniela.entity.pojo.Team;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface MatchRepository extends JpaRepository<Match, Long>, JpaSpecificationExecutor<Match> {

	Page<Match> findByMatchDayDivisionSeason(Season season, Pageable pageable);
	
	boolean existsByLocalTeamOrAwayTeam(Team localTeam, Team awayTeam);

	Page<Match> findByIsActive(Boolean isActive, Pageable pageable);

	Page<Match> findByIsActiveAndMatchDay_Division_Season(Boolean isActive, Season season, Pageable pageable);

}
