package rugbyniela.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.Season;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface SeasonRepository extends JpaRepository<Season, Long>, JpaSpecificationExecutor<Season> {

	public Optional<Season> findByIsActiveTrue();
	public Optional<Season> findByIdAndIsActiveTrue(Long id);
	boolean existsByName(String name);
	public Page<Season> findByIsActiveTrue(Pageable pageable);
	public Page<Season> findByIsActive(Boolean isActive, Pageable pageable);
}
