package rugbyniela.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import rugbyniela.entity.pojo.Division;
import rugbyniela.entity.pojo.Season;
import rugbyniela.entity.pojo.Team;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface TeamRepository extends JpaRepository<Team, Long>, JpaSpecificationExecutor<Team> {
	
	boolean existsByName(String name);

	@Query("SELECT t FROM Division d JOIN d.teams t WHERE d.season = :season AND d.id = :divisionId ORDER BY t.name")Page<Team> findTeamsBySeasonAndDivision(@Param("season")Season season, @Param("divisionId")Long divisionId, Pageable pageable);

	}
