package rugbyniela.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.TeamDivisionScore;

/**
* Generated by Spring Data Generator on 03/02/2026
*/
@Repository
public interface TeamDivisionScoreRepository extends JpaRepository<TeamDivisionScore, Long>, JpaSpecificationExecutor<TeamDivisionScore> {

}
