package rugbyniela.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import jakarta.transaction.Transactional;
import rugbyniela.entity.pojo.Token;

/**
* Generated by Spring Data Generator on 17/12/2025
*/
@Repository
public interface TokenRepository extends JpaRepository<Token, Long>, JpaSpecificationExecutor<Token> {

	//to get all tokens of a user by its id
	@Query(value = """
	        select t from Token t inner join User u\s
	        on t.user.id = u.id\s
	        where u.id = :userId and (t.expired = false or t.revoked = false)\s
	        """)
	List<Token> findAllValidTokenByUser(@Param("userId")Long userId);
	//to logout
	Optional<Token> findByToken(String token);
	@Modifying //Indicates this query will change data (delete/update)
	@Transactional //needed to ensure that if it fails, the DB does not break
	@Query(value = "delete from Token t where t.expired = true or t.revoked = true")
	void deleteAllExpiredOrRevokedTokens();
}
