package rugbyniela.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import rugbyniela.entity.pojo.User;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {

	Optional<User> findByEmail(String email);
	public boolean existsByEmail(String email);

	public boolean existsByPhoneNumber(String phoneNumber);

	public boolean existsByInstagram(String instagram);
	
	public boolean existsByIdAndCurrentCoalitionIsNotNull(Long id);
}
