package rugbyniela.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import rugbyniela.entity.pojo.Season;
import rugbyniela.entity.pojo.User;
import rugbyniela.entity.pojo.UserSeasonScore;

/**
* Generated by Spring Data Generator on 20/11/2025
*/
@Repository
public interface UserSeasonScoreRepository extends JpaRepository<UserSeasonScore, Long>, JpaSpecificationExecutor<UserSeasonScore> {

	public Optional<UserSeasonScore> findByUserAndSeason(User u, Season s);
}
